### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by kisyular** [kisyular/MI-449-SS17-740-js-firebase-intro-T4LtxO#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://kisyular-kgucykegmdzxwt4ltxo.surge.sh/) and meets the following criteria:

- [x] Use [this code](https://gist.github.com/egillespie/942cc3aed19977590b431c10333736c2) as a foundation for your project
- [x] Your own Firebase project is used to store all of the site's messages
- [x] A message and its creation time are added to the database when Enter is pressed or Woof is clicked
- [x] Messages are stored in the database according to the structure in `model.json`
- [x] Anyone can edit any message by clicking the pencil icon, typing a new message, and pressing Enter
- [x] Anyone can delete any message by clicking the red X icon
- [x] When a message is added, edited, or deleted, _Recent woofs_ automatically updates for everyone viewing the page
- [x] Use the `TODO` comments in `woofer-db.js` as your guide for placing code

**Comment by egillespie** [comment]
Hi @kisyular, you're off to a great start! 🌮 There are a few small quirks worth pointing out and address:

### `woofer-db.js` does not pass linting

You have a mix of `'` and `"` characters as well as a rogue `;` character that are preventing your JavaScript from passing linting.

### All woofs are assigned the same `created_at` time

```js
var createTime = Date.now()
// CREATE a new woof in Firebase
function createWoofInDatabase (woof) {
  // TODO create a new record in Firebase
  woof = woofText.value
  firebase.database().ref("woof").push({
    created_at: createTime,
    text: woof
  })
}
```

There are a couple of things wrong with the above code:

1. Your `createTime` is only assigned once when the page first loads, which causes all woofs in that browser tab to be given the same `created_at` time.
2. The `woof` that is being passed to `createWoofInDatabase` already has a `created_at` property and you are overriding it. You can simply call `push(woof)`.

### Updating the woof text removes `created_at` from the database

```js
firebase.database().ref('woof').child(woofKey).set({
  text:woofText
})
```

The code above overwrites the whole woof record in the database. If you edit the woof text and then refresh the page, you can see that the time of the woof changes. If you look at that woof in the Firebase console, you'll see that it is missing the `created_at` property.

To fix this, you'll need to get a reference to the `text` field and then set just the text. There's an example in the lesson. 😉 

### No need to call `deleteWoof()` in `woofer-db.js`

You are calling `deleteWoof()` in two places in `woofer-db.js`. This function is already called in `woofer-ui.js` when the red X button is clicked so you can remove those two lines from your code without any side-effects.

---

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! 🏎💨

**Comment by kisyular** [comment]
@egillespie 

1. I implemented your suggestions. The update function does not overwrite the created_at time now. It only updates the text.
2. I have used single quotes for all my 'string' variables
3. To avoid the linting issues, which were caused majorly calling functions from another script, I have combined the script into one script. This has solved a lot of linter warning. I hope this is not "illegal" in this project.
4. The remaining linter problems I am not sure how to solve them, these are caused by warning like 

- _**Warning	js-standard	'moment' is not defined.	21:4**_
- _**Warning	js-standard	'firebase' is not defined.	111:1**_

**Comment by egillespie** [comment]
Sorry for not giving you a heads-up about those other linter warnings! You don't need to worry about them, and combining files to reduce the number of them is fine (again, my bad). There is a link in Slack that explains how to get rid of them though (in case you're curious).

The only thing that stands out to me now is this:

```js
function createWoofInDatabase (woof) {
  // TODO create a new record in Firebase
  woof = woofText.value
  firebase.database().ref('woof').push({
    created_at: new Date().getTime(),
    text: woof})
}
```

This is still more code than is necessary. `createWoofInDatabase` is passed a `woof` parameter that already has `text` and `created_at` properties in it, so all you have to do is call `push(woof)`. No need to call `woofText.value` or construct a new object.

Take another stab at it and if you have any questions, let me know! 🐐

**Comment by kisyular** [comment]
Hellow I made the changes to

`function createWoofInDatabase (woof) {
  // TODO create a new record in Firebase
  // woof = woofText.value
  firebase.database().ref('woof').push(woof)
}`

Kindly take a look and lemme know. Thank you

**Comment by egillespie** [comment]
Nailed it! 🔨 :shipit:
